### ISSUE TITLE
Missing id?

### ISSUE THREAD

**Issue by Blaisorblade** [ekmett/groupoids#1]
As you write, groupoids are categories with inverses - but then groupoids should have an `id` member, probably by inheriting from Category. Why is it not there?

I'm confused about your comment
"This technically should be a category with inverses, except we need to use Ob to define the valid objects for the category": what is Ob there? It's not a member of Category or Semigroupoids, so I'm quite confused.

**Comment by ekmett** [comment]
http://hackage.haskell.org/package/semigroupoids-5.1/docs/Data-Semigroupoid-Ob.html
